name: "CI"
on: 
  push:
    branches:
      - master
    
env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout master
        with:
          fetch-depth: 0
      
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm ci

      - name: Update package.json versions
        run: NX_CLOUD_DISTRIBUTED_EXECUTION=false npx nx affected --target=version --parallel --max-parallel=2 -- --patch

      - name: Deploy npm packages
        run: NX_CLOUD_DISTRIBUTED_EXECUTION=false npx nx affected --target=deploy --parallel --max-parallel=2

      - name: Stop agents
        run: npx nx-cloud stop-all-agents
    
  agents: 
    runs-on: ubuntu-latest
    name: Agent
    timeout-minutes: 10
    strategy:
      matrix:
        agent: [1,2]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      
      - name: Install dependencies
        run: npm i

      - name: Start NX agent ${{ matrix.agent }}
        run: npx nx-cloud start-agent
